Update brew list command
Homebrew has begun emitting a deprecation warning when checking for
requirements on osx as of Homebrew/brew#8851

Example output when installing a Ruby:

```
rvm install 2.7.2
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.15/x86_64/ruby-2.7.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Warning: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead.
... (repeated ~12 times on my system)
Warning: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
...
```

This does not impact the execution, and the command completes
successfully, however it's extra noise for the end user.

The `--formula` flag was added back in August in Homebrew/brew#8229
and brew will auto-update in most scenarios - but users who have set the
environment variable to not auto-update brew may fail this command with:

    Error: ambiguous option: --formula

I do not have any insight when brew may handle the deprecation warning
and remove the existing behavior.

Signed-off-by: Mike Fiedler <miketheman@gmail.com>